<template>
<AppHeader />
<img class="hero-image" src="/assets/images/projects/ai-brand-kit/cover.webp" alt="AI Brand Kit cover">

<main class="page project-page">
    <aside class="page-side"><ProjectSectionNav /></aside>

    <article class="content page-main">
        <header class="project-header">
            <p class="project-kicker">2026</p>
            <h1>AI Brand Kit</h1>
            <p class="lead">Partnering with TikTok Life Services to help an AI agent generate on-brand H5 pages and
                header images.</p>
        </header>

        <dl class="project-facts">
            <div><dt>Timeline</dt><dd>Jun – Aug 2026</dd></div>
            <div><dt>Team</dt><dd>1 Product Manager, 3 Developers, 3 Operations</dd></div>
            <div><dt>Role</dt><dd>AI Product Design Intern @TikTok</dd></div>
            <div><dt>Methods</dt><dd>Comparative evaluation (LoRA vs. skill), agent design, iterative testing</dd></div>
        </dl>

        <p class="statement"><span class="statement-label">Research question</span>Can a designer's tacit sense of
            “on brand” be written down as rules an AI agent can follow?</p>

        <section id="abstract">
            <h2>Abstract</h2>
            <p class="lead">“Make it look better” cannot guide an agent. Visual quality becomes repeatable only when
                taste is translated into concrete constraints.</p>
            <figure class="figure-float">
                <img src="/assets/images/projects/ai-brand-kit/kv-02.webp" alt="Generated Life Services key visual">
                <figcaption>A Life Services key visual generated by the workflow.</figcaption>
            </figure>
            <p>TikTok Life Services operations teams can generate campaign pages on an internal agent platform, but
                the output is often generic and off-brand. I compared two ways of teaching the agent the brand — a
                fine-tuned LoRA and a written skill — and the skill produced better on-brand images. I then built a
                two-skill workflow that takes a campaign brief to a header image and a complete H5 page, and iterated
                on it by cataloguing how the output failed and encoding a fix for each failure.</p>
        </section>

        <section id="context">
            <h2>Context</h2>
            <p class="lead">Life Services teams need polished, on-brand campaign visuals and H5 pages, often and
                fast.</p>
            <p>Making each page by hand with designers is slow. The agent platform lets operations teams generate
                pages themselves, but the visual quality is inconsistent and rarely matches the brand. There are two
                broad ways to give a generative system a brand's style: adapt the model's weights (for example with a
                LoRA, Hu et al., 2021), or leave the model alone and write the style down as instructions, references,
                and scripts an agent follows step by step. The second keeps the rules readable and editable by
                designers — if it works.</p>
            <p>The goals were a <strong>higher baseline</strong> (output starts on-brand), <strong>wider
                adoption</strong> (operations teams stop queuing for design support), and <strong>faster
                turnaround</strong> (brief to page in one pass).</p>
        </section>

        <section id="method">
            <h2>Method</h2>
            <h3>01 — LoRA vs. skill</h3>
            <!-- TODO(research): describe the comparison — how many images per approach, what criteria (logo accuracy,
                 style match, text quality…), and who judged them. Even “12 images each, rated by 3 designers” is enough. -->
            <p>I generated header images with both approaches and compared them on image quality and fit with the Life
                Services visual style. The comparison <strong>favored the skill</strong>, which became the foundation
                for the rest of the workflow.</p>

            <h3>02 — From a linear chain to templates</h3>
            <p>The first workflow was a linear chain: campaign topic → generated prompt → generated image. It
                <strong>rarely met the quality bar</strong>, and the style repeated itself across campaigns. I replaced
                it with <strong>prompt templates organized by topic category</strong>: the skill classifies the
                campaign, picks the matching template, and composes a prompt from it.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/prompt-canvas.webp" alt="Working canvas showing a logo reference and category reference images fanning out into prompt threads and their generated header images">
                <figcaption>The working canvas: a logo reference and category references fanning out into prompt
                    threads and their generated header images.</figcaption>
            </figure>

            <h3>03 — Failure-driven iteration</h3>
            <p>I tested the agent round by round, recorded each recurring failure, and changed the reference inputs,
                prompts, scripts, or skill steps to address it — working with developers on specific issues such as
                removing the background behind a generated title.</p>

            <h3>04 — Encoding the H5 page</h3>
            <p>I analyzed sample H5 pages to decide which parts of the layout could be <strong>encoded as a
                skill</strong>, then defined a template for each page section, with the HTML and CSS knowledge needed to
                reproduce them consistently — including a typographic treatment that keeps section subtitles on
                brand.</p>
        </section>

        <section id="system">
            <h2>System</h2>
            <p class="lead">Two skills: one for the header image, one for the H5 page built from it.</p>

            <h3>Skill 01 — Header image generation</h3>
            <p>Turns a campaign theme into a ready-to-use Life Services key visual. The SKILL.md steps:</p>
            <ol>
                <li>Define the campaign theme</li>
                <li>Classify it into one of seven categories</li>
                <li>Draft three titles, pick one</li>
                <li>Compose the prompt from the template</li>
                <li>Generate against two reference images</li>
                <li>Overlay the auto-coloured logo</li>
            </ol>
            <figure>
                <div class="figure-grid figure-grid--3">
                    <img src="/assets/images/projects/ai-brand-kit/kv-04.webp" alt="Travel campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-05.webp" alt="Matcha campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-06.webp" alt="Tea campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-07.webp" alt="Late-night food campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-08.webp" alt="Summer picnic campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-09.webp" alt="Beauty campaign key visual">
                </div>
                <figcaption>Key visuals for travel, matcha, tea, late-night food, summer picnic, and beauty
                    campaigns.</figcaption>
            </figure>

            <h3>Skill 02 — H5 page generation</h3>
            <figure class="figure-float">
                <img src="/assets/images/projects/ai-brand-kit/h5-set.webp" alt="Four generated H5 campaign pages: restaurant discovery, summer water play, winter pet travel, and spring blossom">
                <figcaption>Four generated H5 pages: restaurant discovery, summer water play, winter pet travel, and
                    spring blossom.</figcaption>
            </figure>
            <p>Extends the approved key visual into a complete, responsive H5 page. The SKILL.md steps:</p>
            <ol>
                <li>Confirm inputs and real content</li>
                <li>Generate or receive the key visual</li>
                <li>Analyze the key visual</li>
                <li>Build the brand kit</li>
                <li>Select modules, set page order</li>
                <li>Plan title images and cutouts</li>
                <li>Implement in HTML and CSS</li>
                <li>Check compliance, then deliver</li>
            </ol>
            <p>Python scripts inside the skill handle what the image model can't do reliably: background removal,
                blending the picture into the background, and inserting the logo.</p>
        </section>

        <section id="findings">
            <h2>Findings</h2>
            <p class="lead">Four recurring failures — a small taxonomy of where an image model breaks brand rules, and
                what fixed each one.</p>
            <!-- TODO(research): if you logged outputs, add before/after pass rates for each failure type (e.g. “logo
                 correct in 4/12 → 11/12 images”). This turns the taxonomy into evidence. -->
            <!-- Element repetition: hidden for now, no supporting image yet.
                 Decorative elements repeated excessively within one composition. -->
            <h3>Logo distortion</h3>
            <p>The logo rendered with the wrong shape, or appeared more than once. Taking the logo out of generation —
                reserving its space and overlaying the approved asset afterwards — addressed it.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-logo.webp" alt="Problem and solution for the logo: inconsistent renders beside the reference sheet of approved heart-logo treatments">
                <figcaption>Logo: inconsistent renders, beside the reference sheet of approved treatments.</figcaption>
            </figure>
            <h3>Title collision</h3>
            <p>The space reserved for the logo was not respected, so the title overlapped it. A blending script now
                keeps the top of the image clear.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-title.webp" alt="Problem and solution for title placement: an overlapping title beside the script-blended version that reserves space at the top">
                <figcaption>Title placement: the overlapping title, and the script-blended version that keeps the top
                    clear.</figcaption>
            </figure>
            <h3>Wrong typeface</h3>
            <p>Generated text rendered in a typeface outside the brand set.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-typeface.webp" alt="Campaign titles before and after, three samples each side">
                <figcaption>Campaign titles before and after.</figcaption>
            </figure>
            <h3>Over-stylization</h3>
            <p>The overall render skewed more cartoonish than the brand allows.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-style.webp" alt="Nine header images before and after, showing the shift away from a cartoonish render">
                <figcaption>Nine header images before and after, moving away from a cartoonish render.</figcaption>
            </figure>
            <p class="statement">Pattern: what the model does unreliably (exact logos, reserved space) moved into
                deterministic scripts; what it does well (mood, composition) stayed in the prompt.</p>
        </section>

        <section id="discussion">
            <h2>Discussion</h2>
            <h3>From taste to rules</h3>
            <p>References only became useful once they were translated into concrete visual, content, and layout
                constraints. Writing the skill was, in effect, making a designer's judgement explicit — and discovering
                which parts of it could not be written down.</p>
            <h3>Readable rules vs. trained weights</h3>
            <p>A skill can be read, reviewed, and edited by designers and operations staff; a LoRA cannot. That
                transparency may matter as much as image quality when a team has to maintain a brand over time.</p>
            <h3>Limitations</h3>
            <p>The workflow was tested on sample campaigns during a three-month internship. It has not yet been
                validated on real production requests with measurable quality feedback, and details are limited by
                confidentiality.</p>
        </section>

        <section id="open-questions">
            <h2>Open questions</h2>
            <ol class="open-questions">
                <li>Which parts of a designer's taste resist being written as rules — and what should happen to
                    them?</li>
                <li>How should non-designers be able to tell whether an agent's output is on brand?</li>
                <li>Can a skill learn from the campaigns that performed well, the way
                    <a href="/projects/aigc-video-automation">AIGC Video Automation</a> began to?</li>
            </ol>
        </section>

        <section id="contribution">
            <h2>Contribution</h2>
            <p>I designed both skills end to end — the LoRA comparison, the category templates, the SKILL.md steps,
                the reference sets, and the failure fixes — and worked with developers on the scripts.</p>
            <!-- TODO(research): confirm this split with what the PM, developers, and operations team did. -->
            <p><strong>Tools:</strong> agent skills (SKILL.md), prompt engineering, Python, HTML/CSS.</p>
        </section>

        <section id="references">
            <h2>References</h2>
            <ol class="references">
                <li>Hu, E. J., Shen, Y., Wallis, P., Allen-Zhu, Z., Li, Y., Wang, S., Wang, L., &amp; Chen, W. (2021).
                    LoRA: Low-Rank Adaptation of Large Language Models. <em>arXiv:2106.09685.</em></li>
            </ol>
        </section>
    </article>
</main>
<AppFooter />
</template>

<script setup>
useHead({
  title: 'AI Brand Kit',
  link: [
    { rel: 'icon', type: 'image/png', href: '/assets/images/main/logo.svg' },
    { rel: 'stylesheet', href: '/css/styles.css' },
    { rel: 'stylesheet', href: '/css/project.css' }
  ],
  script: [
    { src: '/js/script.js', body: true },
    { src: '/js/project.js', body: true }
  ]
});
</script>
