<template>
<AppHeader />
<img class="hero-image" src="/assets/images/projects/ai-brand-kit/cover.webp" alt="AI Brand Kit cover">

<main class="page project-page">
    <aside class="page-side"><ProjectSectionNav /></aside>

    <article class="content page-main">
        <header class="project-header">
            <p class="project-kicker">2026</p>
            <h1>AI Brand Kit</h1>
            <p class="lead">Partnering with TikTok Life Services to help an AI agent generate on-brand H5 pages and
                header images.</p>
        </header>

        <dl class="project-facts">
            <div><dt>Timeline</dt><dd>Jun – Aug 2026</dd></div>
            <div><dt>Team</dt><dd>1 Product Manager, 3 Developers, 3 Operations</dd></div>
            <div><dt>Role</dt><dd>AI Product Design Intern @TikTok</dd></div>
            <div><dt>Skills</dt><dd>Agent Design, Prompt Engineering</dd></div>
        </dl>

        <section id="overview">
            <h2>Overview</h2>
            <p class="lead">I designed a two-skill workflow that moves an AI agent from a campaign brief to a key
                visual and a complete H5 page.</p>
            <figure class="figure-float">
                <img src="/assets/images/projects/ai-brand-kit/kv-02.webp" alt="Generated Life Services key visual">
                <figcaption>A Life Services key visual generated by the workflow.</figcaption>
            </figure>
            <p>The work covered four parts:</p>
            <ul>
                <li><strong>Brand knowledge</strong> — analyzing and understanding the brand's visual language and
                    assets.</li>
                <li><strong>Visual generation</strong> — generating high-quality header images that place the logo
                    well, match the campaign brief, and fit the brand's style.</li>
                <li><strong>H5 page generation</strong> — extending the header image into a complete H5 page, with
                    elements and content that align with the brand.</li>
                <li><strong>Python scripts</strong> — scripts inside the skill that assist page generation: background
                    removal, blending the picture into the background, inserting the logo, and more.</li>
            </ul>
            <p class="statement">How might we help an AI agent create Life Services H5 pages and header images that meet
                a high visual standard — without making every campaign a manual design task?</p>
        </section>

        <section id="problem">
            <h2>Problem</h2>
            <p class="lead">Life Services teams frequently need campaign visuals and H5 pages that are polished,
                on-brand, and ready to use.</p>
            <p>Creating these pages one by one with designers and operations teams can be time-consuming. The agent
                platform lets operations teams generate pages directly, improving speed and efficiency — but the visual
                quality can be inconsistent and often fails to fully match the brand style.</p>
            <p>The skills aim to address this problem specifically:</p>
            <h3>Wider adoption</h3>
            <p>Operations teams create their own campaign visuals and H5 pages on the agent platform instead of
                queuing for design support.</p>
            <h3>Higher baseline</h3>
            <p>Life Services visual standards live inside the workflow, so output starts on-brand rather than
                generic.</p>
            <h3>Faster turnaround</h3>
            <p>A campaign brief becomes a finished header image and H5 page in a single pass.</p>
        </section>

        <section id="solution">
            <h2>Solution</h2>
            <p class="lead">Two skills: one for the header image, one for the H5 page built from it.</p>

            <h3>Skill 01 — Header image generation</h3>
            <p>Turns a campaign theme into a ready-to-use Life Services key visual. The SKILL.md steps:</p>
            <ol>
                <li>Define the campaign theme</li>
                <li>Classify it into one of seven categories</li>
                <li>Draft three titles, pick one</li>
                <li>Compose the prompt from the template</li>
                <li>Generate against two reference images</li>
                <li>Overlay the auto-coloured logo</li>
            </ol>
            <figure>
                <div class="figure-grid figure-grid--3">
                    <img src="/assets/images/projects/ai-brand-kit/kv-04.webp" alt="Travel campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-05.webp" alt="Matcha campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-06.webp" alt="Tea campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-07.webp" alt="Late-night food campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-08.webp" alt="Summer picnic campaign key visual">
                    <img src="/assets/images/projects/ai-brand-kit/kv-09.webp" alt="Beauty campaign key visual">
                </div>
                <figcaption>Key visuals for travel, matcha, tea, late-night food, summer picnic, and beauty
                    campaigns.</figcaption>
            </figure>

            <h3>Skill 02 — H5 page generation</h3>
            <figure class="figure-float">
                <img src="/assets/images/projects/ai-brand-kit/h5-set.webp" alt="Four generated H5 campaign pages: restaurant discovery, summer water play, winter pet travel, and spring blossom">
                <figcaption>Four generated H5 pages: restaurant discovery, summer water play, winter pet travel, and
                    spring blossom.</figcaption>
            </figure>
            <p>Extends the approved key visual into a complete, responsive H5 page. The SKILL.md steps:</p>
            <ol>
                <li>Confirm inputs and real content</li>
                <li>Generate or receive the key visual</li>
                <li>Analyze the key visual</li>
                <li>Build the brand kit</li>
                <li>Select modules, set page order</li>
                <li>Plan title images and cutouts</li>
                <li>Implement in HTML and CSS</li>
                <li>Check compliance, then deliver</li>
            </ol>
        </section>

        <section id="process">
            <h2>Process</h2>
            <h3>01 — LoRA vs. skill</h3>
            <p>I evaluated two approaches, a LoRA and a skill, on which produced higher-quality images that fit the
                Life Services visual style. The comparison <strong>favored the skill</strong>, which became the
                foundation for the rest of the workflow.</p>

            <h3>02 — Header image skill</h3>
            <p>The initial workflow was a linear chain: campaign topic, then generated prompt, then generated image. In
                practice it <strong>rarely met the quality bar</strong>, and the resulting style repeated itself across
                campaigns.</p>
            <p>I replaced it with a set of <strong>prompt templates organized by topic category</strong>. The skill now
                assigns the template that matches the campaign and composes a prompt from it, addressing both the
                quality ceiling and the repetition.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/prompt-canvas.webp" alt="Working canvas showing a logo reference and category reference images fanning out into prompt threads and their generated header images">
                <figcaption>The working canvas: a logo reference and category references fanning out into prompt
                    threads and their generated header images.</figcaption>
            </figure>

            <h3>03 — Problem solving</h3>
            <p>Problems occurred in the process that affected the quality of the output. I iterated on reference
                inputs, script writing, prompt engineering, and additional steps in the skill to resolve each of these,
                bringing the output to a <strong>consistent quality level</strong>.</p>
            <!-- Element repetition: hidden for now, no supporting image yet.
                 Decorative elements repeated excessively within one composition. -->
            <p><strong>Logo distortion.</strong> The logo rendered with an incorrect shape, or appeared more than once
                in a single image.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-logo.webp" alt="Problem and solution for the logo: inconsistent renders beside the reference sheet of approved heart-logo treatments">
                <figcaption>Logo: inconsistent renders, beside the reference sheet of approved treatments.</figcaption>
            </figure>
            <p><strong>Title collision.</strong> The space reserved for the logo at the top of the image was not
                respected, so the title overlapped it.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-title.webp" alt="Problem and solution for title placement: an overlapping title beside the script-blended version that reserves space at the top">
                <figcaption>Title placement: the overlapping title, and the script-blended version that keeps the top
                    clear.</figcaption>
            </figure>
            <p><strong>Wrong typeface.</strong> Generated text rendered in a typeface outside the brand set.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-typeface.webp" alt="Campaign titles before and after, three samples each side">
                <figcaption>Campaign titles before and after.</figcaption>
            </figure>
            <p><strong>Over-stylization.</strong> The overall render skewed more cartoonish than the brand allows.</p>
            <figure>
                <img src="/assets/images/projects/ai-brand-kit/issue-style.webp" alt="Nine header images before and after, showing the shift away from a cartoonish render">
                <figcaption>Nine header images before and after, moving away from a cartoonish render.</figcaption>
            </figure>

            <h3>04 — H5 page skill</h3>
            <p>I analyzed the sample H5 pages to determine which parts of the layout could be <strong>encoded as a
                    skill</strong>, then defined a template for each page section. The skill is written with HTML and
                CSS knowledge so pages can be reproduced consistently, including a typographic treatment for section
                subtitles that keeps them on brand. I then <strong>tested the agent and revised the skill round by
                    round</strong> to improve the output, working with developers to resolve specific issues such as
                removing the background behind a generated title.</p>
        </section>

        <!-- <section id="reflection">
            <h2>Reflection</h2>
            <p class="lead">Visual quality becomes repeatable only when it is designed as a system.</p>
            <h3>From taste to rules</h3>
            <p>“Make it look better” cannot guide an agent. References become useful when they are translated into
                concrete visual, content, and layout constraints.</p>
            <h3>What comes next</h3>
            <p>The next step is expanding the sample library and validating the workflow with real production requests
                and measurable quality feedback.</p>
        </section> -->

        <section class="next-project-section">
            <h2>More projects</h2>
            <ProjectGrid :items="pickProjects('/projects/orangobranding', '/projects/paletteu')" />
        </section>
    </article>
</main>
<AppFooter />
</template>

<script setup>
useHead({
  title: 'AI Brand Kit',
  link: [
    { rel: 'icon', type: 'image/png', href: '/assets/images/main/logo.svg' },
    { rel: 'stylesheet', href: '/css/styles.css' },
    { rel: 'stylesheet', href: '/css/project.css' }
  ],
  script: [
    { src: '/js/script.js', body: true },
    { src: '/js/project.js', body: true }
  ]
});
</script>
